DROP TABLE IF EXISTS raw.landmarks_cleaned;
CREATE TABLE raw.landmarks_cleaned (
  "PID"                     text,
  "Title"                   text,
  "Description"             text,
  "Identifier"              text,
  "Format"                  text,
  "Type"                    text,
  "Access rights statement" text,
  "Copyright statement"     text,
  "Relationship"            text,
  "Digital URI"             text,
  "ILMS Identifier"         text,
  "ILMS URI"                text,
  "Creator/Contributor"     text,
  "Date"                    text,
  "Location"                text,
  latitude                  double precision,
  longitude                 double precision,
  region                    text,
  distance_from_cbd         double precision,
  -- landmark category flags (10)
  is_building               boolean,
  is_church                 boolean,
  is_park                   boolean,
  is_street                 boolean,
  is_historic               boolean,
  is_cultural               boolean,
  is_commercial             boolean,
  is_government             boolean,
  is_transport              boolean,
  is_architectural          boolean,
  -- derived
  feature_count             integer,
  feature_diversity         integer,
  description_length        integer,
  title_length              integer,
  historical_period         text,
  landmark_type             text
);
